/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DeviceCard: typeof import('./components/DeviceCard.vue')['default']
    DeviceControlModal: typeof import('./components/DeviceControlModal.vue')['default']
    HotspotPanel: typeof import('./components/HotspotPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SceneCard: typeof import('./components/SceneCard.vue')['default']
    StatCard: typeof import('./components/StatCard.vue')['default']
  }
}
